language: python

# Required for Python 3.7+.
#   See: https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905
dist: xenial
stages:
  - test
  - deploy

matrix:
    include:
        - python: 3.6
          env: TOXENV=py36
        - python: 3.7
          env: TOXENV=py37
        - python: 3.8
          env: TOXENV=py38,reqs
        - python: 3.8
          env: TOXENV=pep8,mypy
        - python: 3.8
          env: TOXENV=docs

before_install:
       - sudo apt-get -y install graphviz gnuplot-nox ghostscript
       - sudo apt-get -y install lmodern
       - sudo apt-get -y install latexmk texlive texlive-latex-extra texlive-generic-extra texlive-xetex 
       - sudo apt-get -y install texlive-font-utils texlive-fonts-recommended texlive-fonts-extra

install:
  # Ensure virtualenv is up to date to avoid DeprecationWarning in bundled site.py.
  - pip install --upgrade virtualenv
  - pip install tox

script:
  tox

notifications:
  email: false

